included:
  - MyRec/MyRec

excluded:
  - Pods
  - DerivedData
  - .build
  - plan
  - docs
  - scripts
  - .github
  - .git
  - .claude
  - MyRec.xcodeproj

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_parameters
  - closure_spacing
  - sorted_imports

disabled_rules:
  - trailing_whitespace

line_length:
  warning: 120
  error: 200
  ignores_comments: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
  excluded:
    - id
    - x
    - y
